name: RECOVERY

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'RECOVERY URL'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out
      uses: actions/checkout@main

    - name: Prepare the environment
      run: |
        sudo apt install git wget lz4 tar openssl python3 -y

    - name: Run Patch Script
      run: |
        chmod +x run.sh
        ./run.sh ${{ github.event.inputs.RECOVERY_URL }}

    - name: Upload Recovery
      uses: actions/upload-artifact@v4
      with:
        path: output/*.tar
        name: Patched-Recovery


