name: Patch VBMeta for Odin

on:
  workflow_dispatch:
    inputs:
      vbmeta_url:
        description: 'Direct download URL for vbmeta.img'
        required: true
        type: string

jobs:
  patch_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y python3 tar wget

    - name: Download original vbmeta.img
      run: wget -O original_vbmeta.img ${{ github.event.inputs.vbmeta_url }}

    - name: Patch vbmeta.img using Python script
      run: python3 vbmeta.py original_vbmeta.img patched_vbmeta.img

    - name: Create .tar archive for Odin
      run: tar -cvf patched_vbmeta.tar patched_vbmeta.img

    - name: Upload Odin-ready .tar as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: patched_vbmeta.tar
        path: patched_vbmeta.tar
        if-no-files-found: error
